export CT_DEV_PATH=$HOME/workspace/ct
alias vag='cd $CT_DEV_PATH/vagrant'
alias ct='cd $CT_DEV_PATH/'
alias chost='cd $CT_DEV_PATH/Crowdhoster'
alias ch='cd $CT_DEV_PATH/chef'
alias api='cd $CT_DEV_PATH/crowdtilt-internal-api'
alias aspec='cd $CT_DEV_PATH/crowdtilt-api-spec'
alias pub='cd $CT_DEV_PATH/crowdtilt-public-site'
alias vs='vagrant ssh srv1'
alias vu='vagrant up sr1'
alias vk='vagrant destroy srv1'
alias vr='vagrant restart srv1'
alias vp='vagrant provision srv1'
alias vpsql="ssh -t -i ~/.ssh/vagrant vagrant@33.33.33.11 \"sudo su postgres -c 'psql crowdtilt'\""
