#!/bin/bash
HEAD=$(git symbolic-ref HEAD 2> /dev/null)
CUR_BRANCH=${HEAD#refs/heads/}
git push origin $CURR_BRANCH
UPSTREAM=`dirname $(git remote show -n upstream | grep Fetch | cut -d: -f3- | cut -d\/ -f1- )`
echo "UPSTREAM : $UPSTREAM"
BRANCH="dev"
echo "BRANCH: ${BRANCH}"
if [ -n "$1" ]
then
    echo "XXX: $1"
   BRANCH="$1"
fi

hub pull-request -b ${UPSTREAM}:${BRANCH} -h $CUR_BRANCH
echo "${UPSTREAM}:${BRANCH}"


